dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && LANG=\"en_US.UTF-8\""
before_install:
  - eval "${MATRIX_EVAL}"
  - $CXX --version
